{
 "title": "Model Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Model Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 1 },
   "options": {
    "content": "# Model Predictions\n\nThis model is responsible for predicting"
   }
  },
  {
   "title": "Model Score (30m avg)",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(fastapi_regression_model_output_sum[30m])) / sum(rate(fastapi_regression_model_output_count[30m]))"
    }
   ]
  },
  {
   "title": "Model Prediction Distribution",
   "type": "heatmap",
   "description": "Average per second count of predictions which fall into each bucket.",
   "gridPos": { "h": 9, "w": 15, "x": 9, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(fastapi_regression_model_output_bucket[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "Service Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "type": "text",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 11 },
   "options": {
    "content": "# Request Throughput\n\n2xx status codes denote a successful model\nprediction.\n\n4xx status codes are common when clients\nPOST data that does not meet the expected\nschema.\n\nWe calculate the success rate as the percentage\nof HTTP requests that do not return a 5xx code."
   }
  },
  {
   "title": "HTTP Success Rate (30m avg)",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 5, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(fastapi_http_requests_total{status!=\"5xx\"}[30m])) / sum(rate(fastapi_http_requests_total[30m]))"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 15, "x": 9, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fastapi_http_requests_total[1m])) by (status) "
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 20 },
   "options": {
    "content": "# Request Latencies\n\nWe have two SLOs for API latency:\n- Average latency SLO is breached if p50\nlatencies exceed 50ms for 5 minutes.\n- Extreme latency SLO is breached if p99\nlatencies exceed 300ms for 5 minutes.        "
   }
  },
  {
   "title": "Requests In Progress",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 5, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "sum(fastapi_inprogress)" }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 15, "x": 9, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, \n  sum(\n    rate(fastapi_http_request_duration_seconds_bucket[1m])\n  ) by (le)\n)",
     "legendFormat": "99th percentile"
    },
    {
     "expr": "histogram_quantile(0.95, \n  sum(\n    rate(fastapi_http_request_duration_seconds_bucket[1m])\n  ) by (le)\n)",
     "legendFormat": "95th percentile"
    },
    {
     "expr": "histogram_quantile(0.50, \n  sum(\n    rate(fastapi_http_request_duration_seconds_bucket[1m])\n  ) by (le)\n)",
     "legendFormat": "50th percentile"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 29 },
   "options": {
    "content": "# Request Size\n\nThis visualizes the request body sizes for\nthe model predict route. We expect the request\nbody to contain a dictionary with 11 keys with \nall values being floats.         "
   }
  },
  {
   "title": "Request Size (30m avg)",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 5, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(fastapi_http_request_size_bytes_sum{handler=\"/predict\"}[30m])) / sum(rate(fastapi_http_request_size_bytes_count{handler=\"/predict\"}[30m]))"
    }
   ]
  },
  {
   "title": "Request Size",
   "type": "graph",
   "gridPos": { "h": 9, "w": 15, "x": 9, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fastapi_http_request_size_bytes_sum{handler=\"/predict\"}[1m])) / sum(rate(fastapi_http_request_size_bytes_count{handler=\"/predict\"}[1m]))"
    }
   ]
  },
  { "title": "Resource Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } }
 ]
}