apiVersion: apps/v1
kind: Deployment
metadata:
  name: dsi-mlops
  labels:
    app: dsi-mlops
spec:
  selector:
    matchLabels:
      app: dsi-mlops
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: dsi-mlops
    spec:
      containers:
      - name: dsi-mlops
        image: anubhavgarg/olist:0c591d33d8dd15d6b993ec8a44b26b4638dd7a43
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: dsi-mlops
  labels:
    app: dsi-mlops
spec:
  ports:
  - port: 5000
    protocol: TCP
    name: dsi-mlops
  selector:
    app: dsi-mlops
  type: LoadBalancer

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: dsi-mlops-servicemonitor
  # must by the same namespace that Prometheus is running in
  namespace: monitoring
  labels:
    app: dsi-mlops
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app: dsi-mlops
  endpoints:
    - path: metrics
      port: app
      interval: 15s
  namespaceSelector:
    any: true

